# Numpy

In [12]:
# Vector: 3i + 7j + 5k -->1D
# matrix -->2d

In [13]:
a = np.array([3, 4, 7])
a

array([3, 4, 7])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.arange(1, 7, 2)

array([1, 3, 5])

In [18]:
np.arange(0,1,0.02)

array([0.  , 0.02, 0.04, 0.06, 0.08, 0.1 , 0.12, 0.14, 0.16, 0.18, 0.2 ,
       0.22, 0.24, 0.26, 0.28, 0.3 , 0.32, 0.34, 0.36, 0.38, 0.4 , 0.42,
       0.44, 0.46, 0.48, 0.5 , 0.52, 0.54, 0.56, 0.58, 0.6 , 0.62, 0.64,
       0.66, 0.68, 0.7 , 0.72, 0.74, 0.76, 0.78, 0.8 , 0.82, 0.84, 0.86,
       0.88, 0.9 , 0.92, 0.94, 0.96, 0.98])

In [19]:
np.append(a, [2,3])

array([3, 4, 7, 2, 3])

In [23]:
np.delete(a, [2,3])

IndexError: index 3 is out of bounds for axis 0 with size 3

In [27]:
np.sort(a)

array([3, 4, 7])

In [28]:
arr = np.array([2,3,9,5,31,7])
np.sort(arr)

array([ 2,  3,  5,  7,  9, 31])

In [35]:
arr2 = np.array([
    [1,2,3,4],
    [4,5,6,7],
    [8,9,10,11]
])
arr2.ndim

2

In [36]:
arr2.size

12

## Reshaping

In [40]:
arr = np.array([4,7,1,11,10,19,21,5])
arr_reshape = arr.reshape(2,4)
arr_reshape.ndim

2

In [44]:
arr.reshape(2,2,2)

array([[[ 4,  7],
        [ 1, 11]],

       [[10, 19],
        [21,  5]]])

In [48]:
print(arr[np.newaxis])
print(arr[np.newaxis].shape)

[[ 4  7  1 11 10 19 21  5]]
(1, 8)


In [49]:
arr.reshape(1,8)

array([[ 4,  7,  1, 11, 10, 19, 21,  5]])

In [50]:
arr.reshape(8,1)

array([[ 4],
       [ 7],
       [ 1],
       [11],
       [10],
       [19],
       [21],
       [ 5]])

In [54]:
np.expand_dims(arr, axis=1)

array([[ 4],
       [ 7],
       [ 1],
       [11],
       [10],
       [19],
       [21],
       [ 5]])

## Indexing and Slicing

In [56]:
mylist = [1,2,3,4,5,6,7,8]
mylist[1:4]

[2, 3, 4]

In [59]:
data = np.array([1,2,3,4,5,6,7,8])
data[1:4]

array([2, 3, 4])

In [60]:
data[-2:]

array([7, 8])

In [61]:
data[data>=5]

array([5, 6, 7, 8])

In [64]:
data[(data > 4) & (data%2==0)]

array([6, 8])

In [65]:
arr1= arr[0:4]
arr2= arr[4: ]

In [66]:
arr1

array([ 4,  7,  1, 11])

In [67]:
arr2

array([10, 19, 21,  5])

In [68]:
np.vstack((arr1,arr2))

array([[ 4,  7,  1, 11],
       [10, 19, 21,  5]])

In [69]:
a1 = np.array([
    [1,2],
    [3,4],
])
a2 = np.array([
    [5,6],
    [7,8],
])

In [70]:
np.vstack((a1,a2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [73]:
# Vstack horizontal
np.hstack((arr1,arr2))

array([ 4,  7,  1, 11, 10, 19, 21,  5])

In [74]:
np.hstack((a1,a2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [9]:
arrsplit = np.array([
    [4,5,6,7,8,9,10,11],
    [12,13,14,15,16,17,18,19,20]
])

C:\Users\Fatimah Zahra\AppData\Local\Temp\ipykernel_13704\1615557811.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arrsplit = np.array([


In [79]:
np.hsplit(arrsplit, 2)

[array([list([4, 5, 6, 7, 8, 9, 10, 11])], dtype=object),
 array([list([12, 13, 14, 15, 16, 17, 18, 19, 20])], dtype=object)]

In [81]:
arr2 = arr.copy()
arr2

array([ 4,  7,  1, 11, 10, 19, 21,  5])

## Basic Operation

In [82]:
v1 = np.array([2,3,5])
v2 = np.array([1,2,4])


In [83]:
v1+v2

array([3, 5, 9])

In [84]:
v1 - v2

array([1, 1, 1])

In [85]:
v1*v2

array([ 2,  6, 20])

In [86]:
v1/v2

array([2.  , 1.5 , 1.25])

In [87]:
data

array([1, 2, 3, 4, 5, 6, 7, 8])

In [89]:
a1.sum()

10

In [91]:
a1.sum(axis=1)


array([3, 7])

In [92]:
v1

array([2, 3, 5])

In [93]:
v1 * .5

array([1. , 1.5, 2.5])

In [94]:
np.arange(0,16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [96]:
m = np.arange(0,16).reshape(4,4)

In [97]:
m.sum(axis=1)

array([ 6, 22, 38, 54])

In [98]:
m.min()

0

In [101]:
m.min(axis=0)

array([0, 1, 2, 3])

In [102]:
m.mean(axis=1)

array([ 1.5,  5.5,  9.5, 13.5])

In [103]:
# 0 untuk baris, 1 untuk kolom

## Matrix

In [105]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [106]:
np.random.random((3,3))

array([[0.77332609, 0.81447766, 0.32145974],
       [0.37020085, 0.36218237, 0.65304318],
       [0.16178493, 0.29962523, 0.3666012 ]])

In [108]:
mtr = np.array([
    [1,2],
    [3,4]
])

In [109]:
ones = np.ones((2,2))

In [110]:
mtr + ones

array([[2., 3.],
       [4., 5.]])

mtr + 5

In [111]:
mtr + 5

array([[6, 7],
       [8, 9]])

In [112]:
mtr + np.array([2,3])

array([[3, 5],
       [5, 7]])

In [113]:
mtr * mtr

array([[ 1,  4],
       [ 9, 16]])

In [114]:
np.matmul(mtr,mtr)

array([[ 7, 10],
       [15, 22]])

In [115]:
np.dot(mtr,mtr)

array([[ 7, 10],
       [15, 22]])

In [121]:
M = np.random.random((5,5))
M

array([[0.04814145, 0.11702228, 0.43762088, 0.77455364, 0.9379471 ],
       [0.82551956, 0.82416754, 0.42023984, 0.49883795, 0.20254605],
       [0.6133269 , 0.51872856, 0.96414383, 0.32002436, 0.79357624],
       [0.88811273, 0.29721028, 0.80911544, 0.8060453 , 0.65925992],
       [0.17909322, 0.10401284, 0.73716232, 0.94066864, 0.51048264]])

In [124]:
M[3,3]

0.8060452977659699

In [125]:
M[2, 1:4]

array([0.51872856, 0.96414383, 0.32002436])

In [126]:
M.min(axis=0)

array([0.04814145, 0.10401284, 0.42023984, 0.32002436, 0.20254605])

In [147]:
M

array([[0.04814145, 0.11702228, 0.43762088, 0.77455364, 0.9379471 ],
       [0.82551956, 0.82416754, 0.42023984, 0.49883795, 0.20254605],
       [0.6133269 , 0.51872856, 0.96414383, 0.32002436, 0.79357624],
       [0.88811273, 0.29721028, 0.80911544, 0.8060453 , 0.65925992],
       [0.17909322, 0.10401284, 0.73716232, 0.94066864, 0.51048264]])

In [150]:
np.dot(mtr,np.linalg.inv(mtr))

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [152]:
# Eliminasi
x + 2y = 1
3x + 5y = 2

[1,2] [1]
[3,5] [2]

SyntaxError: invalid syntax (2048107817.py, line 2)

In [155]:
mat_per = np.array([
    [1,2],
    [3,5]
])

mat_has = np.array([1,2])
np.linalg.solve(mat_per,mat_has)

array([-1.,  1.])

## Transpose

In [128]:
Mat = np.array([
    [1,2],
    [3,4],
    [5,6]
])

In [129]:
Mat.T

array([[1, 3, 5],
       [2, 4, 6]])

In [130]:
mat_transposed = Mat.T

In [135]:
mat_transposed.reshape(3,2)

array([[1, 3],
       [5, 2],
       [4, 6]])

In [138]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [141]:
one_3d = np.random.random((3,3,3))

In [142]:
one_3d.mean()

0.5493685736483487

In [143]:
one_3d.shape

(3, 3, 3)

In [144]:
one_3d.reshape((27, ))

array([0.45701952, 0.16264387, 0.50075999, 0.1249135 , 0.85476799,
       0.31483561, 0.37454302, 0.38678436, 0.85443774, 0.64681871,
       0.17928622, 0.54143017, 0.21394525, 0.78008174, 0.85495502,
       0.7583825 , 0.20904821, 0.68155801, 0.73908796, 0.93507126,
       0.97781748, 0.62899692, 0.40904478, 0.75889793, 0.63072061,
       0.15553799, 0.70156514])

In [146]:
one_3d.flatten()

array([0.45701952, 0.16264387, 0.50075999, 0.1249135 , 0.85476799,
       0.31483561, 0.37454302, 0.38678436, 0.85443774, 0.64681871,
       0.17928622, 0.54143017, 0.21394525, 0.78008174, 0.85495502,
       0.7583825 , 0.20904821, 0.68155801, 0.73908796, 0.93507126,
       0.97781748, 0.62899692, 0.40904478, 0.75889793, 0.63072061,
       0.15553799, 0.70156514])

In [4]:
data_aktual = np.random.random(100)

In [6]:
data_prediksi = np.random.random(100)

In [7]:
(1/len(data_aktual)) * np.sum(np.square(data_aktual - data_prediksi))

0.16149579808348768